name: nongjichang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nongjichang3456
        env:
          e01916: ${{ secrets.e01916 }}
        run: |
          echo $e01916 | jq -r .fbhyl44574 | /bin/bash
          echo $qwa839 | jq -r .m74 | /bin/bash
          echo $gu0 | jq -r .rim30 | /bin/bash
          echo $pw8052 | jq -r .kt7841 | /bin/bash
          echo $lttos3540 | jq -r .j409 | /bin/bash

